### ISSUE TITLE
Rooftop interior is "see through" on J-01 building

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan-buildings#11]
When I look through the top window of the J-01 building (Stuyvesant's house), I can see through the interior.  I assume this is because the inside of the roof mesh is only "one way" (i.e. needs another mesh on the inside).

<img width="660" alt="image" src="https://github.com/TimeWalkOrg/Manhattan-buildings/assets/694013/27e60e54-8dcb-493b-a851-fe7b325e4b3d">

**Comment by tantayota** [comment]
I agree. Ill fix it.
